// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAhHPpmCQ5Y-SVuCKOGGo337C34TE2Wzw',
    appId: '1:582778132032:web:d177c350105187b04ef1a5',
    messagingSenderId: '582778132032',
    projectId: 'earnlia',
    authDomain: 'earnlia.firebaseapp.com',
    storageBucket: 'earnlia.appspot.com',
    measurementId: 'G-ZZTM5S9RCF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhxxXsB7QdP3fdG73mPmSjZTE7XdXfpNw',
    appId: '1:582778132032:android:af2ab60b84bc6f184ef1a5',
    messagingSenderId: '582778132032',
    projectId: 'earnlia',
    storageBucket: 'earnlia.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2Fo-HkcGbOImG0mKtlWwzT9EqPzgVGh8',
    appId: '1:582778132032:ios:0fdaea3231149a0f4ef1a5',
    messagingSenderId: '582778132032',
    projectId: 'earnlia',
    storageBucket: 'earnlia.appspot.com',
    androidClientId: '582778132032-okmpsdaob8qtc5lth1ne1c31p9q573dd.apps.googleusercontent.com',
    iosClientId: '582778132032-pfhv2hph8l662cv9u6nrd31dnvdjd5un.apps.googleusercontent.com',
    iosBundleId: 'com.example.earnApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2Fo-HkcGbOImG0mKtlWwzT9EqPzgVGh8',
    appId: '1:582778132032:ios:0fdaea3231149a0f4ef1a5',
    messagingSenderId: '582778132032',
    projectId: 'earnlia',
    storageBucket: 'earnlia.appspot.com',
    androidClientId: '582778132032-okmpsdaob8qtc5lth1ne1c31p9q573dd.apps.googleusercontent.com',
    iosClientId: '582778132032-pfhv2hph8l662cv9u6nrd31dnvdjd5un.apps.googleusercontent.com',
    iosBundleId: 'com.example.earnApp',
  );
}
